### PR TITLE
add ECOOP 2016, ECOOP 2017, OOPSLA 2016, PLDI 2016

### PR DESCRIPTION
**Pull request by csgordon**

### CODE REVIEW

**Comment by msridhar** [comment]
Who should have checked the open PRs before opening #20 @csgordon 😄

**Comment by csgordon** [comment]
Hah!  Yeah, let's merge.  I don't have time to stare at this stuff until later tonight myself, but I just gave you push access to my repository --- if you push changes, it will update this PR.

If you're confident in your vetting vs. DBLP, then I'd default to your version of names.  I did this late at night a few weeks ago, so I don't remember how systematically I compared to DBLP.

**Comment by msridhar** [comment]
Ok, all my changes are now pushed here.  I think I missed EPC/ERC for PLDI'17, will try to add later today.

**Comment by franktip** [comment]
Just added data for ISSTA/FSE/ICSE 2016-2017.  Does anyone have time to add data for POPL 2016/2017?

**Comment by csgordon** [comment]
I can do at least part of it now

**Comment by csgordon** [comment]
I've got POPL 2016 in my fork; I'll come back later for POPL 2017

**Pull request merged**
